<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecurityGuard.Core\SecurityGuard.Core.csproj" />
    <ProjectReference Include="..\SecurityGuard.Storage\SecurityGuard.Storage.csproj" />
    <ProjectReference Include="..\SecurityGuard.Infrastructure\SecurityGuard.Infrastructure.csproj" />
    <ProjectReference Include="..\SecurityGuard.AlgorithmGuard\SecurityGuard.AlgorithmGuard.csproj" />
    <ProjectReference Include="..\SecurityGuard.TransferGuard\SecurityGuard.TransferGuard.csproj" />
  </ItemGroup>

</Project>