<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecurityGuard.Core\SecurityGuard.Core.csproj" />
    <ProjectReference Include="..\SecurityGuard.Storage\SecurityGuard.Storage.csproj" />
    <ProjectReference Include="..\SecurityGuard.Infrastructure\SecurityGuard.Infrastructure.csproj" />
  </ItemGroup>

</Project>