<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecurityGuard.Core\SecurityGuard.Core.csproj" />
    <ProjectReference Include="..\SecurityGuard.Storage\SecurityGuard.Storage.csproj" />
    <ProjectReference Include="..\SecurityGuard.Infrastructure\SecurityGuard.Infrastructure.csproj" />
    <ProjectReference Include="..\SecurityGuard.AlgorithmGuard\SecurityGuard.AlgorithmGuard.csproj" />
    <ProjectReference Include="..\SecurityGuard.TransferGuard\SecurityGuard.TransferGuard.csproj" />
    <ProjectReference Include="..\SecurityGuard.ArchiveGuard\SecurityGuard.ArchiveGuard.csproj" />
  </ItemGroup>

</Project>